# Generated by Django 5.2.4 on 2026-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('partner_admin', 'Partner Admin'), ('contractor', 'Contractor')], default='contractor', max_length=20),
        ),
    ]
